replicaCount: 1

image:
  repository: 307217365914.dkr.ecr.us-east-1.amazonaws.com/trendlink-app
  tag: 6616a5c8f7c37e4d615f68674de00d7ae0f6b535
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: trendlink.local
  path: /prospect-agent

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

env:
  AWS_REGION: us-east-1
  DYNAMODB_TABLE: trendlink-prospects

vault:
  role: tl-prospect-agent
  googlePlacesSecret: secret/data/trendlink/google-places-api-key
  awsSecret: secret/data/trendlink/aws-credentials