replicaCount: 1

image:
  repository: 307217365914.dkr.ecr.us-east-1.amazonaws.com/trendlink-app
  tag: 23218a524b4687dec7cfc5bc898d89b87d56607c
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: trendlink.local
  path: /prospect-agent

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"

env:
  AWS_REGION: us-east-1
  DYNAMODB_TABLE: trendlink-prospects

vault:
  role: tl-prospect-agent
  googlePlacesSecret: secret/data/trendlink/google-places-api-key
  awsSecret: secret/data/trendlink/aws-credentials