apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "tl-test"
        vault.hashicorp.com/agent-inject-secret-test: "secret/data/test"
    spec:
      serviceAccountName: tl-test-sa
      containers:
        - name: sample
          image: 307217365914.dkr.ecr.us-east-1.amazonaws.com/trendlink-app:7bbbda16d131c915dc1062bf965162b816077911
          ports:
            - containerPort: 80